POST https://fe-test.zojapay.com/api/admin/register
Content-Type: application/json

{
    "first_name": "echoes",
    "last_name": "willieams",
    "email": "willl@gmail.com",
    "password": "Password1!"
}